/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicAside: typeof import('./src/components/Layout/basicAside.vue')['default']
    BasicHeader: typeof import('./src/components/Layout/BasicHeader.vue')['default']
    BasicLayout: typeof import('./src/components/Layout/BasicLayout.vue')['default']
    BasicSidebar: typeof import('./src/components/Layout/BasicSidebar.vue')['default']
    BasicTabs: typeof import('./src/components/Layout/BasicTabs.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./src/components/Layout/Header.vue')['default']
    Login: typeof import('./src/components/Auth/Login.vue')['default']
    Page: typeof import('./src/components/Home/Page.vue')['default']
    Sidebar: typeof import('./src/components/Layout/Sidebar.vue')['default']
    Tabs: typeof import('./src/components/Layout/Tabs.vue')['default']
    VueApp: typeof import('./src/components/ui/VueApp.vue')['default']
  }
}
